import App from 'next/app'
import '../styles/globals.css'
import 'antd/dist/antd.css'
 import '../styles/components/header.css'
 import '../styles/index.css'
 import '../styles/components/author.css'
 import '../styles/components/footer.css'
 import '../styles/components/advert.css'
 import '../styles/detailed.css'
export default App